// <auto-generated />
using System;
using CorrecaoFp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CorrecaoFp.Data.Migrations
{
    [DbContext(typeof(ControladorFpContext))]
    [Migration("20240216143651_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CorrecaoFp.Business.Models.Capacitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Capacitor_ID");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT")
                        .HasColumnName("Capacitor_Fabricante");

                    b.Property<double>("Potencia")
                        .HasColumnType("REAL")
                        .HasColumnName("Capacitor_Potencia");

                    b.Property<double>("Tensao")
                        .HasColumnType("REAL")
                        .HasColumnName("Capacitor_Tensao");

                    b.Property<string>("Unidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("Capacitor_Unidade");

                    b.HasKey("Id");

                    b.ToTable("Capacitor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fabricante = "WEG",
                            Potencia = 0.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 2,
                            Fabricante = "WEG",
                            Potencia = 0.5,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 3,
                            Fabricante = "WEG",
                            Potencia = 0.75,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 4,
                            Fabricante = "WEG",
                            Potencia = 1.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 5,
                            Fabricante = "WEG",
                            Potencia = 1.5,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 6,
                            Fabricante = "WEG",
                            Potencia = 2.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 7,
                            Fabricante = "WEG",
                            Potencia = 2.5,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 8,
                            Fabricante = "WEG",
                            Potencia = 3.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 9,
                            Fabricante = "WEG",
                            Potencia = 5.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 10,
                            Fabricante = "WEG",
                            Potencia = 7.5,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 11,
                            Fabricante = "WEG",
                            Potencia = 10.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 12,
                            Fabricante = "WEG",
                            Potencia = 12.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 13,
                            Fabricante = "WEG",
                            Potencia = 15.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 14,
                            Fabricante = "WEG",
                            Potencia = 17.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 15,
                            Fabricante = "WEG",
                            Potencia = 20.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 16,
                            Fabricante = "WEG",
                            Potencia = 25.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        },
                        new
                        {
                            Id = 17,
                            Fabricante = "WEG",
                            Potencia = 30.0,
                            Tensao = 220.0,
                            Unidade = "kVAr"
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Configuracao_ID");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Configuracao_Descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("Configuracao_Nome");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL")
                        .HasColumnName("Configuracao_Valor");

                    b.HasKey("Id");

                    b.ToTable("Configuracao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Quantidade de estágios fixos",
                            Nome = "QUANTIDADE_ESTAGIOS_FIXOS",
                            Valor = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Quantidade de estágios automáticos",
                            Nome = "QUANTIDADE_ESTAGIOS_AUTOMATICOS",
                            Valor = 12.0
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Tensão de linha (V)",
                            Nome = "TENSAO_LINHA",
                            Valor = 127.0
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Relação de transformação do transformador de corrente (TC)",
                            Nome = "RELACAO_TC",
                            Valor = 800.0
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.Estagio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Estagio_ID");

                    b.Property<int>("CapacitorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Capacitor_ID");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Estagio_Descricao");

                    b.Property<int>("TipoPotenciaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tipo_Potencia_ID");

                    b.HasKey("Id");

                    b.HasIndex("CapacitorId");

                    b.HasIndex("TipoPotenciaId");

                    b.ToTable("Estagio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 1",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CapacitorId = 2,
                            Descricao = "Potência do estárgio 2",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CapacitorId = 3,
                            Descricao = "Potência do estárgio 3",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 4,
                            CapacitorId = 4,
                            Descricao = "Potência do estárgio 4",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CapacitorId = 5,
                            Descricao = "Potência do estárgio 5",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 6,
                            CapacitorId = 6,
                            Descricao = "Potência do estárgio 6",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 7,
                            CapacitorId = 7,
                            Descricao = "Potência do estárgio 7",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 8,
                            CapacitorId = 8,
                            Descricao = "Potência do estárgio 8",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 9,
                            CapacitorId = 9,
                            Descricao = "Potência do estárgio 9",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 10,
                            CapacitorId = 10,
                            Descricao = "Potência do estárgio 10",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 11,
                            CapacitorId = 11,
                            Descricao = "Potência do estárgio 11",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 12,
                            CapacitorId = 12,
                            Descricao = "Potência do estárgio 12",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 13,
                            CapacitorId = 13,
                            Descricao = "Potência do estárgio 13",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 14,
                            CapacitorId = 14,
                            Descricao = "Potência do estárgio 14",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 15,
                            CapacitorId = 15,
                            Descricao = "Potência do estárgio 15",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 16,
                            CapacitorId = 16,
                            Descricao = "Potência do estárgio 16",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 17,
                            CapacitorId = 17,
                            Descricao = "Potência do estárgio 17",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 18,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 18",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 19,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 19",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 20,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 20",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 21,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 21",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 22,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 22",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 23,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 23",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 24,
                            CapacitorId = 1,
                            Descricao = "Potência do estárgio 24",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 25,
                            CapacitorId = 12,
                            Descricao = "Potência do estágio fixo 1",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 26,
                            CapacitorId = 13,
                            Descricao = "Potência do estágio fixo 2",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 27,
                            CapacitorId = 13,
                            Descricao = "Potência do estágio fixo 3",
                            TipoPotenciaId = 1
                        },
                        new
                        {
                            Id = 28,
                            CapacitorId = 13,
                            Descricao = "Potência do estágio fixo 4",
                            TipoPotenciaId = 1
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.Medicao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Medicao_ID");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("Medicao_DataInicio");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("Medicao_DataFim");

                    b.Property<double>("FatorPotencia")
                        .HasColumnType("REAL")
                        .HasColumnName("Medicao_FatorPotencia");

                    b.Property<double>("PotenciaAparente")
                        .HasColumnType("REAL")
                        .HasColumnName("Medicao_PotenciaAparente");

                    b.Property<double>("PotenciaAtiva")
                        .HasColumnType("REAL")
                        .HasColumnName("Medicao_PotenciaAtiva");

                    b.Property<double>("PotenciaReativa")
                        .HasColumnType("REAL")
                        .HasColumnName("Medicao_PotenciaReativa");

                    b.Property<string>("TipoFatorPotencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("Medicao_TipoFatorPotencia");

                    b.HasKey("Id", "DataInicio");

                    b.ToTable("Medicao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInicio = new DateTime(2023, 6, 1, 8, 15, 10, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 6, 1, 8, 30, 10, 0, DateTimeKind.Unspecified),
                            FatorPotencia = 0.96999999999999997,
                            PotenciaAparente = 14769.799999999999,
                            PotenciaAtiva = 14326.780000000001,
                            PotenciaReativa = -2881.5799999999999,
                            TipoFatorPotencia = "Cap"
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.ModoCompensacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Modo_Compensacao_ID");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("Modo_Compensacao_Nome");

                    b.HasKey("Id");

                    b.ToTable("Modo_Compensacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "PFW03-M12 (Modo inteligente)"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sequencial Ascendente"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Sequencial Descendente"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Linear"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Circular"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Manual"
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.TipoPotencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tipo_Potencia_ID");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo_Potencia_Descricao");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo_Potencia_Sigla");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Potencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Capacitor Trifásico",
                            Sigla = "C"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Reator de Derivação Trifásico",
                            Sigla = "L"
                        });
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.Estagio", b =>
                {
                    b.HasOne("CorrecaoFp.Business.Models.Capacitor", "Capacitor")
                        .WithMany("Estagios")
                        .HasForeignKey("CapacitorId")
                        .IsRequired();

                    b.HasOne("CorrecaoFp.Business.Models.TipoPotencia", "TipoPotencia")
                        .WithMany("Estagios")
                        .HasForeignKey("TipoPotenciaId")
                        .IsRequired();

                    b.Navigation("Capacitor");

                    b.Navigation("TipoPotencia");
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.Capacitor", b =>
                {
                    b.Navigation("Estagios");
                });

            modelBuilder.Entity("CorrecaoFp.Business.Models.TipoPotencia", b =>
                {
                    b.Navigation("Estagios");
                });
#pragma warning restore 612, 618
        }
    }
}
